

# try:
#     # Code that may raise an exception
#     x = int(input("Enter a number: "))
#     result = 10 / x
#     print("Result:", result)
# except ZeroDivisionError:
#     print("Cannot divide by zero!")
# except ValueError:
#     print("Please enter a valid number!")
# except Exception as e:
#     print("An unexpected error occurred:", e)


# try : 
#     print(name)
# except Exception as error:
#     print("Exception",error)
# finally :
#     print("finally")

# print("Continue ...")
